# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0835c30e0176cc96b303502c4d64d22d504f7a019adab32b23ece1e0ca6e33168709ab5599c4e13ca3892942879679dbb50520ff9d299b2f241c122220ecb42b

test:
  secret_key_base: c46a5d3148159852678c9b5836a0a70376fc11ae57d60d9d13b23c8a9c015d83c319e28d173ad1a98a4c3f97e0f39d344f6235c12263ef77ea0d9ea067d81ff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
